import requests
import os
import json
import base64
from html_parser import HTMLParser
from utils import TextSplitter
from dotenv import load_dotenv
print(os.listdir("."))
load_dotenv()

class ImageResponder:
    def __init__(self, api_key: str, endpoint: str) -> None:
        self.api_key = api_key
        self.endpoint = endpoint
        self.parser = HTMLParser()
        self.headers = {
            "Content-Type": "application/json",
            "api-key": self.api_key,
        }

    def _question_answer(self, prompt:str, encoded_image: str) -> str:
        '''
        Internal method to process a question and get an answer using AI for the provided image.
        
        Args:
            encoded_image (str): Base64 encoded image string.
        
        Returns:
            str: The answer generated by the AI.
        '''
        payload = {
            "messages": [
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": prompt},
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpg;base64,{encoded_image}"
                            },
                        },
                    ]
                }
            ],
            "temperature": 0.7,
            "top_p": 0.95,
            "max_tokens": 2000
        }

        try:
            response = requests.post(self.endpoint, headers=self.headers, json=payload)
            response.raise_for_status()
        except requests.RequestException as e:
            print(f"Failed to make the request. Error: {e}")
            return "Error in fetching the answer."
        
        answer = response.json().get("choices", [{}])[0].get("message", {}).get("content", "")
        return answer

if __name__ == "__main__":
    image_responder = ImageResponder(api_key=os.getenv("API_KEY"), endpoint=os.getenv("ENDPOINT"))
    
    #同階層のsample.jpgをbase64エンコード
    with open("sample2.png", "rb") as image_file:
        encoded_image = base64.b64encode(image_file.read()).decode("utf-8")
    print(encoded_image)
    answer = image_responder._question_answer(encoded_image)
    print(answer)